# Generated by Django 3.2.8 on 2021-10-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DFT', 'Draft'), ('SBM', 'Submitted'), ('PUBL', 'Published'), ('REJ', 'Rejected')], default='DFT', max_length=4),
        ),
    ]
